apiVersion: v1
kind: Service
metadata:
  name: devops-service
  namespace:  devops
spec:
  type: NodePort
  selector:
    app: devops
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
